services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - pg_database
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  pg_database:
    external: true


